### ISSUE TITLE
Doesn't work with latest Kobalt

### ISSUE THREAD

**Issue by sargunster** [kmruiz/kobalt-jacoco#4]
Getting this on Kobalt 0.806

***** ERROR Error: java.lang.NoSuchMethodError: com.beust.kobalt.api.IDependencyManager$DefaultImpls.create$default(Lcom/beust/kobalt/api/IDependencyManager;Ljava/lang/String;Lcom/beust/kobalt/api/Project;ILjava/lang/Object;)Lcom/beust/kobalt/api/IClasspathDependency;
*****

**Comment by kmruiz** [comment]
I checked it and I think it's solved. Can you try the version 0.1.3?

Thanks!!

**Comment by sargunster** [comment]
Yep, it works!
